const RateLimitActionTypes = {
  FETCH_RATE_LIMIT_START: 'FETCH_RATE_LIMIT_START',
  FETCH_RATE_LIMIT_SUCCESS: 'FETCH_RATE_LIMIT_SUCCESS',
  FETCH_RATE_LIMIT_FAILURE: 'FETCH_RATE_LIMIT_FAILURE',
}

export default RateLimitActionTypes;
